version: "1"
services:
  db:
    image: postgres:alpine3.19
    restart: always
    environment:
      POSTGRES_PASSWORD: "PROD"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "PROD"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "PROD", "-U", "postgres" ]
      interval: 5s
      timeout: 60s
      retries: 20
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app_data
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_PASSWORD: PROD
      DB_USER: postgres
    depends_on:
      db:
        condition: service_healthy
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      app:
        condition: service_healthy
volumes:
  db-data:
  backend_data:
    driver: local
