version: "1"
services:
  app:
    build:
      context: ../
      dockerfile: backend/Dockerfile
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_PASSWORD: PROD
      DB_USER: postgres
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:alpine3.19
    restart: always
    environment:
      POSTGRES_PASSWORD: "PROD"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "PROD"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "PROD", "-U", "postgres" ]
      interval: 5s
      timeout: 60s
      retries: 20
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db-data:
